[package]
name = "miden-prover"
version = "0.10.3"
description = "Miden VM prover"
documentation = "https://docs.rs/miden-prover/0.10.3"
readme = "README.md"
categories = ["cryptography", "emulators", "no-std"]
keywords = ["miden", "prover", "stark", "zkp"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[features]
concurrent = ["processor/concurrent", "std", "winter-prover/concurrent"]
default = ["webgpu"]
metal = ["dep:miden-gpu", "dep:elsa", "dep:pollster", "concurrent", "std"]
webgpu = ["dep:miden-gpu", "dep:elsa", "miden-gpu/webgpu", "async"]
async = ["maybe-async/async", "winter-prover/async", "winter-prover/async-trait", "dep:async-trait"]
std = ["air/std", "processor/std", "winter-prover/std", "miden-gpu/std", "tracing/std"]

[dependencies]
air = { package = "miden-air", path = "../air", version = "0.10", default-features = false }
processor = { package = "miden-processor", path = "../processor", version = "0.10", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }
winter-prover = { package = "winter-prover", version = "0.9", default-features = false }
maybe-async = { package = "winter-maybe-async", version = "0.9", default-features = false }
async-trait = { version = "0.1", optional = true }

[target.'cfg(all(target_arch = "aarch64", target_os = "macos"))'.dependencies]
elsa = { version = "1.9", optional = true }
miden-gpu = { git = "https://github.com/0xPolygonMiden/miden-gpu", rev = "b77b4709d69d42ef663ed5ea41f48f8b165f59f2", default-features = false, optional = true }
pollster = { version = "0.3", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
miden-gpu = { git = "https://github.com/0xPolygonMiden/miden-gpu", rev = "b77b4709d69d42ef663ed5ea41f48f8b165f59f2", default-features = false, optional = true }
